# Generated by Django 5.0.4 on 2024-09-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newbakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='sorts')),
                ('category', models.CharField(max_length=255)),
                ('current_price', models.CharField(default='NGN', max_length=20)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('flavour', models.CharField(max_length=80)),
                ('layers_display', models.TextField()),
                ('cakecategoryIdentifier', models.CharField(max_length=30)),
            ],
        ),
    ]
