# Generated by Django 5.0.4 on 2024-09-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addProducts', '0002_itemsort'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemSort',
        ),
    ]
